env:
  browser: true
  es2021: true
  node: true
  mocha: true
extends: airbnb-base
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  radix: off
  no-console: off
